base: /
baseVariants: []
dependencies:
  - binder-gmbh/binder-defence-package
languages:
  - languageId: 0
    title: English
    enabled: true
    base: /en/
    locale: en_US.UTF-8
    navigationTitle: English
    flag: gb
    typo3Language: default
  - languageId: 1
    title: Deutsch
    enabled: true
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    typo3Language: de
    fallbackType: free
  - languageId: 2
    title: Français
    enabled: true
    base: /fr/
    locale: fr_FR.UTF-8
    navigationTitle: Français
    flag: fr
    typo3Language: fr
    fallbackType: free
rootPageId: 1
routes: []
websiteTitle: Binder Defence
